homeassistant:
  name: BAY ST
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

http:
  api_password: !secret api_password
  server_port: 8123
  base_url: !secret base_url
  # ssl_certificate: /etc/letsencrypt/live/hass.example.com/fullchain.pem
  # ssl_key: /etc/letsencrypt/live/hass.example.com/privkey.pem
  # cors_allowed_origins:
  #   - https://google.com
  #   - https://home-assistant.io
  # use_x_forwarded_for: True
  # trusted_networks:
  #   - 127.0.0.1
  #   - 192.168.1.0/24
  #   - 192.168.2.0/24
  #   - 192.168.3.0/24
  #   - 192.168.4.0/24
  # #  - 2001:DB8:ABCD::/48
  ip_ban_enabled: True
  login_attempts_threshold: 3


mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  client_id: home-assistant-opti
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  # protocol: 3.1

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################
###  Devices  ###
group: !include groups.yaml
camera: !include cameras.yaml
sensor: !include sensors.yaml
notify: !include notify.yaml
switch: !include switches.yaml
device_tracker: !include device_trackers.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
automation: !include_dir_merge_list ./automation

# alexa: !include alexa.yaml
# light: !include lights.yaml
# binary_sensor: !include binary_sensors.yaml
# alarm_control_panel: !include alarm_control_panel.yaml
# input_boolean: !include input_boolean.yaml
# input_select: !include input_select.yaml
# shell_command: !include shell_commands.yaml
# remote: !include remote.yaml
# media_player: !include media_players.yaml


####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################
#introduction: # Show links to resources in log and frontend
frontend: # Enables the frontend
updater: # Checks for available updates
discovery: # Discover some devices automatically
conversation: # Allows you to issue voice commands from the frontend in enabled browsers
history: # Enables support for tracking state changes over time.
# logbook: # View all events in a logbook
recorder:
  purge_interval: 5
  purge_keep_days: 180
  db_url: mysql://hass:DB_PASSWORD@192.168.1.100/homeassistant
# logger:
  # default: info
sun: # Track the sun
config: #configuration panel
# logentries:
#   token: !secret logentries_token
ios:

# # Weather Prediction
# sensor:
#   platform: yr


# modbus:
#   type: tcp
#   host: 192.168.3.80
#   port: 502

zwave:
  usb_path: /zwaveusbstick
  # device_config: !include zwave_device_config.yaml
  # new_entity_ids: true

# nest:
#   client_id: !secret nest_client_id
#   client_secret: !secret nest_client_secret

wemo:
  static:
  #   - 192.168.3.62
    - 192.168.3.63
    - 192.168.3.64
    - 192.168.3.65

tts:
  - platform: google


zone 1:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 100
  icon: mdi:castle
  # icon: mdi:account-multiple

zone 2:
  name: Nidhi's Office
  latitude: n-office_latitude
  longitude: n-office_longitude
  radius: 100
  icon: mdi:worker


# usps:
#   username: !secret usps_user
#   password: !secret usps_password



cover:
  - platform: mqtt
    name: Garage Door
    friendly_name: Garage
    state_topic: "garage/door"
    command_topic: "garage/button"
    payload_open: "OPEN"
    payload_close: "OPEN"
    payload_stop: "OPEN"
    state_open: "OPENED"
    state_closed: "CLOSED"
    optimistic: false
    retain: false
    value_template: '{{ value }}'




input_select:
  washer_status:
    name: Washing Machine Status
    options:
      - Idle
      - Running
      - Finishing
      - Clean
    initial: Idle
