- platform: ios
# - platform: pushbullet
#   api_key: !secret pushbullet_api_key
- name: TEXT_DK
  platform: smtp
  server: smtp.gmail.com
  port: 587
  sender: !secret sender_email
  starttls: true
  username: !secret sender_email
  password: !secret sender_email_password
  recipient: !secret dk_sms_email
- name: TEXT_NM
  platform: smtp
  server: smtp.gmail.com
  port: 587
  sender: !secret sender_email
  starttls: true
  username: !secret sender_email
  password: !secret sender_email_password
  recipient: !secret nm_sms_email
