##########################################################################
############################ WASHING MACHINE #############################
##########################################################################

# When we detect power being drawn from the washing machine,
# mark the washing machine as using power
- alias: Set washing machine active when power detected
  trigger:
    - platform: numeric_state
      entity_id: sensor.washer_power
      above: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.washer_status
        state: Idle
      - condition: state
        entity_id: input_select.washer_status
        state: Running
      - condition: state
        entity_id: input_select.washer_status
        state: Finishing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washer_status
        option: Running



# When the power level drops below 10, and the washing machine is set to
# the 'Running' state, mark the washing machine as Finished

- alias: Set washing machine finishing when power drops
  trigger:
    - platform: numeric_state
      entity_id: sensor.washer_power
      below: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washer_status
        state: Running
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washer_status
        option: Finishing



# Once the washing machine status has been 'Drying' for 30 minutes, mark the
# washing machine as clean

- alias: Set washing machine clean
  trigger:
    - platform: state
      entity_id: input_select.washer_status
      to: Finishing
      for:
        minutes: 15
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.washer_status
        state: Finishing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washer_status
        option: Clean



# When the power drops and the washing machine is Clean or Finishing, someone has
# turned the washing machine off and emptied it. We should do this when the state
# of the washing machine is clean or Finishing, just incase someone opens the
# washing machine before the 30 minute timeout has been reached.

- alias: Set washing machine Idle when power off
  trigger:
    - platform: numeric_state
      entity_id: sensor.washer_power
      below: 2
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.washer_power
        below: 2
      - condition: or
        conditions:
        - condition: state
          entity_id: input_select.washer_status
          state: Clean
        - condition: state
          entity_id: input_select.washer_status
          state: Finishing
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washer_status
        option: Idle


- alias: Notify iOS Washer Done Soon
  initial_state: true
  hide_entity: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.washer_power
      above: 900
      for:
        minutes: 1
    # - platform: state
    #   entity_id: device_tracker.dksiphone
    #   to: 'home'
    #   for:
    #     minutes: 2
    # - platform: state
    #   entity_id: device_tracker.nmsiphone
    #   to: 'home'
    #   for:
    #     minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.people
        state: 'home'
  action:
    - service: notify.ios_dksphone
      data:
        title: "Washer"
        message: "Will be done soon"




- alias: Notify iOS Washer Finished
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.washer_status
      to: Clean
      for:
        minutes: 1
  condition:
    condition: and
    conditions:
      # - condition: time
      #   before: '22:30:00'
      #   after: '08:29:00'
      - condition: state
        entity_id: group.people
        state: 'home'
      - condition: state
        entity_id: input_select.washer_status
        state: Clean
  action:
    - service: notify.both_phones
      data:
        title: "Washer"
        message: "Move clothes into dryer"
    - service: tts.google_say
      data:
        entity_id: media_player.home_group
        message: "Move clothes into dryer"
